// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.spotinst.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class ElastigroupAzureV3ManagedServiceIdentityArgs extends com.pulumi.resources.ResourceArgs {

    public static final ElastigroupAzureV3ManagedServiceIdentityArgs Empty = new ElastigroupAzureV3ManagedServiceIdentityArgs();

    /**
     * - The name of the Application Security group.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return - The name of the Application Security group.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * - The resource group of the Application Security Group.
     *   }
     * 
     */
    @Import(name="resourceGroupName", required=true)
    private Output<String> resourceGroupName;

    /**
     * @return - The resource group of the Application Security Group.
     * }
     * 
     */
    public Output<String> resourceGroupName() {
        return this.resourceGroupName;
    }

    private ElastigroupAzureV3ManagedServiceIdentityArgs() {}

    private ElastigroupAzureV3ManagedServiceIdentityArgs(ElastigroupAzureV3ManagedServiceIdentityArgs $) {
        this.name = $.name;
        this.resourceGroupName = $.resourceGroupName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ElastigroupAzureV3ManagedServiceIdentityArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ElastigroupAzureV3ManagedServiceIdentityArgs $;

        public Builder() {
            $ = new ElastigroupAzureV3ManagedServiceIdentityArgs();
        }

        public Builder(ElastigroupAzureV3ManagedServiceIdentityArgs defaults) {
            $ = new ElastigroupAzureV3ManagedServiceIdentityArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name - The name of the Application Security group.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name - The name of the Application Security group.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param resourceGroupName - The resource group of the Application Security Group.
         * }
         * 
         * @return builder
         * 
         */
        public Builder resourceGroupName(Output<String> resourceGroupName) {
            $.resourceGroupName = resourceGroupName;
            return this;
        }

        /**
         * @param resourceGroupName - The resource group of the Application Security Group.
         * }
         * 
         * @return builder
         * 
         */
        public Builder resourceGroupName(String resourceGroupName) {
            return resourceGroupName(Output.of(resourceGroupName));
        }

        public ElastigroupAzureV3ManagedServiceIdentityArgs build() {
            $.name = Objects.requireNonNull($.name, "expected parameter 'name' to be non-null");
            $.resourceGroupName = Objects.requireNonNull($.resourceGroupName, "expected parameter 'resourceGroupName' to be non-null");
            return $;
        }
    }

}
