// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.spotinst.aws.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.spotinst.aws.inputs.ElastigroupIntegrationCodedeployDeploymentGroupArgs;
import java.lang.Boolean;
import java.util.List;
import java.util.Objects;


public final class ElastigroupIntegrationCodedeployArgs extends com.pulumi.resources.ResourceArgs {

    public static final ElastigroupIntegrationCodedeployArgs Empty = new ElastigroupIntegrationCodedeployArgs();

    @Import(name="cleanupOnFailure", required=true)
    private Output<Boolean> cleanupOnFailure;

    public Output<Boolean> cleanupOnFailure() {
        return this.cleanupOnFailure;
    }

    @Import(name="deploymentGroups", required=true)
    private Output<List<ElastigroupIntegrationCodedeployDeploymentGroupArgs>> deploymentGroups;

    public Output<List<ElastigroupIntegrationCodedeployDeploymentGroupArgs>> deploymentGroups() {
        return this.deploymentGroups;
    }

    @Import(name="terminateInstanceOnFailure", required=true)
    private Output<Boolean> terminateInstanceOnFailure;

    public Output<Boolean> terminateInstanceOnFailure() {
        return this.terminateInstanceOnFailure;
    }

    private ElastigroupIntegrationCodedeployArgs() {}

    private ElastigroupIntegrationCodedeployArgs(ElastigroupIntegrationCodedeployArgs $) {
        this.cleanupOnFailure = $.cleanupOnFailure;
        this.deploymentGroups = $.deploymentGroups;
        this.terminateInstanceOnFailure = $.terminateInstanceOnFailure;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ElastigroupIntegrationCodedeployArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ElastigroupIntegrationCodedeployArgs $;

        public Builder() {
            $ = new ElastigroupIntegrationCodedeployArgs();
        }

        public Builder(ElastigroupIntegrationCodedeployArgs defaults) {
            $ = new ElastigroupIntegrationCodedeployArgs(Objects.requireNonNull(defaults));
        }

        public Builder cleanupOnFailure(Output<Boolean> cleanupOnFailure) {
            $.cleanupOnFailure = cleanupOnFailure;
            return this;
        }

        public Builder cleanupOnFailure(Boolean cleanupOnFailure) {
            return cleanupOnFailure(Output.of(cleanupOnFailure));
        }

        public Builder deploymentGroups(Output<List<ElastigroupIntegrationCodedeployDeploymentGroupArgs>> deploymentGroups) {
            $.deploymentGroups = deploymentGroups;
            return this;
        }

        public Builder deploymentGroups(List<ElastigroupIntegrationCodedeployDeploymentGroupArgs> deploymentGroups) {
            return deploymentGroups(Output.of(deploymentGroups));
        }

        public Builder deploymentGroups(ElastigroupIntegrationCodedeployDeploymentGroupArgs... deploymentGroups) {
            return deploymentGroups(List.of(deploymentGroups));
        }

        public Builder terminateInstanceOnFailure(Output<Boolean> terminateInstanceOnFailure) {
            $.terminateInstanceOnFailure = terminateInstanceOnFailure;
            return this;
        }

        public Builder terminateInstanceOnFailure(Boolean terminateInstanceOnFailure) {
            return terminateInstanceOnFailure(Output.of(terminateInstanceOnFailure));
        }

        public ElastigroupIntegrationCodedeployArgs build() {
            if ($.cleanupOnFailure == null) {
                throw new MissingRequiredPropertyException("ElastigroupIntegrationCodedeployArgs", "cleanupOnFailure");
            }
            if ($.deploymentGroups == null) {
                throw new MissingRequiredPropertyException("ElastigroupIntegrationCodedeployArgs", "deploymentGroups");
            }
            if ($.terminateInstanceOnFailure == null) {
                throw new MissingRequiredPropertyException("ElastigroupIntegrationCodedeployArgs", "terminateInstanceOnFailure");
            }
            return $;
        }
    }

}
