provider: spotinst
major-version: 3
aws: true
esc:
    enabled: true
env:
    SPOTINST_ACCOUNT: ${{ secrets.SPOTINST_ACCOUNT }}
    SPOTINST_TOKEN: ${{ secrets.SPOTINST_TOKEN }}
    AWS_REGION: "us-west-2"
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
