// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Oceancd.Inputs
{

    public sealed class RolloutSpecStrategyArgArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of an argument.
        /// </summary>
        [Input("argName", required: true)]
        public Input<string> ArgName { get; set; } = null!;

        /// <summary>
        /// Value of an argument.
        /// </summary>
        [Input("argValue")]
        public Input<string>? ArgValue { get; set; }

        /// <summary>
        /// Defines from where to get the value of an argument.
        /// </summary>
        [Input("valueFrom")]
        public Input<Inputs.RolloutSpecStrategyArgValueFromArgs>? ValueFrom { get; set; }

        public RolloutSpecStrategyArgArgs()
        {
        }
        public static new RolloutSpecStrategyArgArgs Empty => new RolloutSpecStrategyArgArgs();
    }
}
