// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Oceancd.Inputs
{

    public sealed class RolloutSpecTrafficAmbassadorGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("mappings", required: true)]
        private InputList<string>? _mappings;

        /// <summary>
        /// A list of names of the Ambassador Mappings used to route traffic to the service.
        /// </summary>
        public InputList<string> Mappings
        {
            get => _mappings ?? (_mappings = new InputList<string>());
            set => _mappings = value;
        }

        public RolloutSpecTrafficAmbassadorGetArgs()
        {
        }
        public static new RolloutSpecTrafficAmbassadorGetArgs Empty => new RolloutSpecTrafficAmbassadorGetArgs();
    }
}
