// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package aws

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-spotinst/sdk/v2/go/spotinst"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "spotinst:aws/beanstalk:Beanstalk":
		r, err = NewBeanstalk(ctx, name, nil, pulumi.URN_(urn))
	case "spotinst:aws/elastigroup:Elastigroup":
		r, err = NewElastigroup(ctx, name, nil, pulumi.URN_(urn))
	case "spotinst:aws/managedInstance:ManagedInstance":
		r, err = NewManagedInstance(ctx, name, nil, pulumi.URN_(urn))
	case "spotinst:aws/mrScalar:MrScalar":
		r, err = NewMrScalar(ctx, name, nil, pulumi.URN_(urn))
	case "spotinst:aws/ocean:Ocean":
		r, err = NewOcean(ctx, name, nil, pulumi.URN_(urn))
	case "spotinst:aws/oceanLaunchSpec:OceanLaunchSpec":
		r, err = NewOceanLaunchSpec(ctx, name, nil, pulumi.URN_(urn))
	case "spotinst:aws/suspension:Suspension":
		r, err = NewSuspension(ctx, name, nil, pulumi.URN_(urn))
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	return
}

func init() {
	version, err := spotinst.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"spotinst",
		"aws/beanstalk",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"spotinst",
		"aws/elastigroup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"spotinst",
		"aws/managedInstance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"spotinst",
		"aws/mrScalar",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"spotinst",
		"aws/ocean",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"spotinst",
		"aws/oceanLaunchSpec",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"spotinst",
		"aws/suspension",
		&module{version},
	)
}
