// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.spotinst;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.spotinst.CredentialsAzureArgs;
import com.pulumi.spotinst.Utilities;
import com.pulumi.spotinst.inputs.CredentialsAzureState;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Provides a Spotinst credential Azure resource.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.spotinst.CredentialsAzure;
 * import com.pulumi.spotinst.CredentialsAzureArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         // set credential Azure
 *         var credential = new CredentialsAzure("credential", CredentialsAzureArgs.builder()
 *             .accountId("act-123456")
 *             .clientId("redacted")
 *             .clientSecret("redacted")
 *             .tenantId("redacted")
 *             .subscriptionId("redacted")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
@ResourceType(type="spotinst:index/credentialsAzure:CredentialsAzure")
public class CredentialsAzure extends com.pulumi.resources.CustomResource {
    /**
     * The ID of the account associated with your token.
     * 
     */
    @Export(name="accountId", refs={String.class}, tree="[0]")
    private Output<String> accountId;

    /**
     * @return The ID of the account associated with your token.
     * 
     */
    public Output<String> accountId() {
        return this.accountId;
    }
    /**
     * Set the application ID.
     * 
     */
    @Export(name="clientId", refs={String.class}, tree="[0]")
    private Output<String> clientId;

    /**
     * @return Set the application ID.
     * 
     */
    public Output<String> clientId() {
        return this.clientId;
    }
    /**
     * Set the key secret.
     * 
     */
    @Export(name="clientSecret", refs={String.class}, tree="[0]")
    private Output<String> clientSecret;

    /**
     * @return Set the key secret.
     * 
     */
    public Output<String> clientSecret() {
        return this.clientSecret;
    }
    /**
     * Set the subscription ID.
     * 
     */
    @Export(name="subscriptionId", refs={String.class}, tree="[0]")
    private Output<String> subscriptionId;

    /**
     * @return Set the subscription ID.
     * 
     */
    public Output<String> subscriptionId() {
        return this.subscriptionId;
    }
    /**
     * Set the directory ID.
     * 
     */
    @Export(name="tenantId", refs={String.class}, tree="[0]")
    private Output<String> tenantId;

    /**
     * @return Set the directory ID.
     * 
     */
    public Output<String> tenantId() {
        return this.tenantId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public CredentialsAzure(java.lang.String name) {
        this(name, CredentialsAzureArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public CredentialsAzure(java.lang.String name, CredentialsAzureArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public CredentialsAzure(java.lang.String name, CredentialsAzureArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("spotinst:index/credentialsAzure:CredentialsAzure", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private CredentialsAzure(java.lang.String name, Output<java.lang.String> id, @Nullable CredentialsAzureState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("spotinst:index/credentialsAzure:CredentialsAzure", name, state, makeResourceOptions(options, id), false);
    }

    private static CredentialsAzureArgs makeArgs(CredentialsAzureArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? CredentialsAzureArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static CredentialsAzure get(java.lang.String name, Output<java.lang.String> id, @Nullable CredentialsAzureState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new CredentialsAzure(name, id, state, options);
    }
}
