// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.spotinst.azure.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class OceanImageMarketplace {
    /**
     * @return Image name.
     * 
     */
    private @Nullable String offer;
    /**
     * @return Image publisher.
     * 
     */
    private @Nullable String publisher;
    /**
     * @return Image Stock Keeping Unit (which is the specific version of the image).
     * 
     */
    private @Nullable String sku;
    /**
     * @return Image version.
     * 
     */
    private @Nullable String version;

    private OceanImageMarketplace() {}
    /**
     * @return Image name.
     * 
     */
    public Optional<String> offer() {
        return Optional.ofNullable(this.offer);
    }
    /**
     * @return Image publisher.
     * 
     */
    public Optional<String> publisher() {
        return Optional.ofNullable(this.publisher);
    }
    /**
     * @return Image Stock Keeping Unit (which is the specific version of the image).
     * 
     */
    public Optional<String> sku() {
        return Optional.ofNullable(this.sku);
    }
    /**
     * @return Image version.
     * 
     */
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(OceanImageMarketplace defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String offer;
        private @Nullable String publisher;
        private @Nullable String sku;
        private @Nullable String version;
        public Builder() {}
        public Builder(OceanImageMarketplace defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.offer = defaults.offer;
    	      this.publisher = defaults.publisher;
    	      this.sku = defaults.sku;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder offer(@Nullable String offer) {
            this.offer = offer;
            return this;
        }
        @CustomType.Setter
        public Builder publisher(@Nullable String publisher) {
            this.publisher = publisher;
            return this;
        }
        @CustomType.Setter
        public Builder sku(@Nullable String sku) {
            this.sku = sku;
            return this;
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {
            this.version = version;
            return this;
        }
        public OceanImageMarketplace build() {
            final var o = new OceanImageMarketplace();
            o.offer = offer;
            o.publisher = publisher;
            o.sku = sku;
            o.version = version;
            return o;
        }
    }
}
