// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Azure.Inputs
{

    public sealed class OceanNpLinuxOsConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("sysctls")]
        private InputList<Inputs.OceanNpLinuxOsConfigSysctlGetArgs>? _sysctls;

        /// <summary>
        /// System Controls
        /// </summary>
        public InputList<Inputs.OceanNpLinuxOsConfigSysctlGetArgs> Sysctls
        {
            get => _sysctls ?? (_sysctls = new InputList<Inputs.OceanNpLinuxOsConfigSysctlGetArgs>());
            set => _sysctls = value;
        }

        public OceanNpLinuxOsConfigGetArgs()
        {
        }
        public static new OceanNpLinuxOsConfigGetArgs Empty => new OceanNpLinuxOsConfigGetArgs();
    }
}
