// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Azure.Inputs
{

    public sealed class OceanNpSchedulingGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// An object used to specify times that the nodes in the virtual node group will be stopped.
        /// </summary>
        [Input("shutdownHours")]
        public Input<Inputs.OceanNpSchedulingShutdownHoursGetArgs>? ShutdownHours { get; set; }

        [Input("suspensionHours")]
        public Input<Inputs.OceanNpSchedulingSuspensionHoursGetArgs>? SuspensionHours { get; set; }

        [Input("tasks")]
        private InputList<Inputs.OceanNpSchedulingTaskGetArgs>? _tasks;
        public InputList<Inputs.OceanNpSchedulingTaskGetArgs> Tasks
        {
            get => _tasks ?? (_tasks = new InputList<Inputs.OceanNpSchedulingTaskGetArgs>());
            set => _tasks = value;
        }

        public OceanNpSchedulingGetArgs()
        {
        }
        public static new OceanNpSchedulingGetArgs Empty => new OceanNpSchedulingGetArgs();
    }
}
