// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Gcp.Inputs
{

    public sealed class ElastigroupRevertToPreemptibleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Valid values: "always", "never", "timeWindow". Required on strategy.revertToPreemptible object.
        /// </summary>
        [Input("performAt", required: true)]
        public Input<string> PerformAt { get; set; } = null!;

        public ElastigroupRevertToPreemptibleArgs()
        {
        }
        public static new ElastigroupRevertToPreemptibleArgs Empty => new ElastigroupRevertToPreemptibleArgs();
    }
}
