// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Gcp.Outputs
{

    [OutputType]
    public sealed class ElastigroupIntegrationGkeAutoscaleDown
    {
        /// <summary>
        /// Number of consecutive periods in which the threshold must be met in order to trigger a scaling action.
        /// </summary>
        public readonly int? EvaluationPeriods;

        [OutputConstructor]
        private ElastigroupIntegrationGkeAutoscaleDown(int? evaluationPeriods)
        {
            EvaluationPeriods = evaluationPeriods;
        }
    }
}
