// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Gke.Inputs
{

    public sealed class OceanImportAutoscalerGetArgs : Pulumi.ResourceArgs
    {
        [Input("autoHeadroomPercentage")]
        public Input<int>? AutoHeadroomPercentage { get; set; }

        [Input("cooldown")]
        public Input<int>? Cooldown { get; set; }

        [Input("down")]
        public Input<Inputs.OceanImportAutoscalerDownGetArgs>? Down { get; set; }

        [Input("headroom")]
        public Input<Inputs.OceanImportAutoscalerHeadroomGetArgs>? Headroom { get; set; }

        [Input("isAutoConfig")]
        public Input<bool>? IsAutoConfig { get; set; }

        [Input("isEnabled")]
        public Input<bool>? IsEnabled { get; set; }

        [Input("resourceLimits")]
        public Input<Inputs.OceanImportAutoscalerResourceLimitsGetArgs>? ResourceLimits { get; set; }

        public OceanImportAutoscalerGetArgs()
        {
        }
    }
}
