// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Ecs.Inputs
{

    public sealed class OceanAutoscalerDownGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Would represent the maximum % to scale-down. Number between 1-100.
        /// </summary>
        [Input("maxScaleDownPercentage")]
        public Input<double>? MaxScaleDownPercentage { get; set; }

        public OceanAutoscalerDownGetArgs()
        {
        }
        public static new OceanAutoscalerDownGetArgs Empty => new OceanAutoscalerDownGetArgs();
    }
}
