// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Aws.Outputs
{

    [OutputType]
    public sealed class ElastigroupIntegrationGitlab
    {
        /// <summary>
        /// Settings for Gitlab runner.
        /// </summary>
        public readonly Outputs.ElastigroupIntegrationGitlabRunner? Runner;

        [OutputConstructor]
        private ElastigroupIntegrationGitlab(Outputs.ElastigroupIntegrationGitlabRunner? runner)
        {
            Runner = runner;
        }
    }
}
