// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Aws.Outputs
{

    [OutputType]
    public sealed class ElastigroupScalingDownPolicyStepAdjustment
    {
        public readonly Outputs.ElastigroupScalingDownPolicyStepAdjustmentAction Action;
        public readonly int Threshold;

        [OutputConstructor]
        private ElastigroupScalingDownPolicyStepAdjustment(
            Outputs.ElastigroupScalingDownPolicyStepAdjustmentAction action,

            int threshold)
        {
            Action = action;
            Threshold = threshold;
        }
    }
}
