// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Aws.Outputs
{

    [OutputType]
    public sealed class ManagedInstanceLoadBalancer
    {
        public readonly string? Arn;
        public readonly bool? AutoWeight;
        public readonly bool? AzAwareness;
        public readonly string? BalancerId;
        /// <summary>
        /// The ManagedInstance name.
        /// </summary>
        public readonly string? Name;
        public readonly string? TargetSetId;
        public readonly string Type;

        [OutputConstructor]
        private ManagedInstanceLoadBalancer(
            string? arn,

            bool? autoWeight,

            bool? azAwareness,

            string? balancerId,

            string? name,

            string? targetSetId,

            string type)
        {
            Arn = arn;
            AutoWeight = autoWeight;
            AzAwareness = azAwareness;
            BalancerId = balancerId;
            Name = name;
            TargetSetId = targetSetId;
            Type = type;
        }
    }
}
