// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Aws.Outputs
{

    [OutputType]
    public sealed class OceanLaunchSpecBlockDeviceMappingEbs
    {
        /// <summary>
        /// Boolean. Flag to delete the EBS on instance termination.
        /// </summary>
        public readonly bool? DeleteOnTermination;
        /// <summary>
        /// Set dynamic IOPS properties. When using this object, you cannot use the `Iops` attribute. You must use one or the other.
        /// </summary>
        public readonly Outputs.OceanLaunchSpecBlockDeviceMappingEbsDynamicIops? DynamicIops;
        /// <summary>
        /// Object. Set dynamic volume size properties. When using this object, you cannot use volumeSize. You must use one or the other.
        /// </summary>
        public readonly Outputs.OceanLaunchSpecBlockDeviceMappingEbsDynamicVolumeSize? DynamicVolumeSize;
        /// <summary>
        /// Boolean. Enables [EBS encryption](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html) on the volume.
        /// </summary>
        public readonly bool? Encrypted;
        /// <summary>
        /// Int. The number of I/O operations per second (IOPS) that the volume supports.
        /// </summary>
        public readonly int? Iops;
        /// <summary>
        /// String. Identifier (key ID, key alias, ID ARN, or alias ARN) for a customer managed CMK under which the EBS volume is encrypted.
        /// </summary>
        public readonly string? KmsKeyId;
        /// <summary>
        /// (Optional) String. The Snapshot ID to mount by.
        /// </summary>
        public readonly string? SnapshotId;
        /// <summary>
        /// The amount of data transferred to or from a storage device per second, you can use this param just in a case that `VolumeType` = `Gp3`.
        /// </summary>
        public readonly int? Throughput;
        /// <summary>
        /// Int. The size, in GB of the volume.
        /// </summary>
        public readonly int? VolumeSize;
        /// <summary>
        /// String. The type of the volume. (Example: `Gp2`).
        /// </summary>
        public readonly string? VolumeType;

        [OutputConstructor]
        private OceanLaunchSpecBlockDeviceMappingEbs(
            bool? deleteOnTermination,

            Outputs.OceanLaunchSpecBlockDeviceMappingEbsDynamicIops? dynamicIops,

            Outputs.OceanLaunchSpecBlockDeviceMappingEbsDynamicVolumeSize? dynamicVolumeSize,

            bool? encrypted,

            int? iops,

            string? kmsKeyId,

            string? snapshotId,

            int? throughput,

            int? volumeSize,

            string? volumeType)
        {
            DeleteOnTermination = deleteOnTermination;
            DynamicIops = dynamicIops;
            DynamicVolumeSize = dynamicVolumeSize;
            Encrypted = encrypted;
            Iops = iops;
            KmsKeyId = kmsKeyId;
            SnapshotId = snapshotId;
            Throughput = throughput;
            VolumeSize = volumeSize;
            VolumeType = volumeType;
        }
    }
}
