// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Aws.Outputs
{

    [OutputType]
    public sealed class OceanLaunchSpecStartupTaint
    {
        /// <summary>
        /// Set startup taint effect.
        /// </summary>
        public readonly string? Effect;
        /// <summary>
        /// Set startup taint key.
        /// </summary>
        public readonly string? Key;
        /// <summary>
        /// Set startup taint value.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private OceanLaunchSpecStartupTaint(
            string? effect,

            string? key,

            string? value)
        {
            Effect = effect;
            Key = key;
            Value = value;
        }
    }
}
