// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.spotinst.aws.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;

@CustomType
public final class OceanLaunchSpecUpdatePolicyRollConfig {
    /**
     * @return Sets the percentage of the instances to deploy in each batch.
     * 
     */
    private Integer batchSizePercentage;

    private OceanLaunchSpecUpdatePolicyRollConfig() {}
    /**
     * @return Sets the percentage of the instances to deploy in each batch.
     * 
     */
    public Integer batchSizePercentage() {
        return this.batchSizePercentage;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(OceanLaunchSpecUpdatePolicyRollConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer batchSizePercentage;
        public Builder() {}
        public Builder(OceanLaunchSpecUpdatePolicyRollConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.batchSizePercentage = defaults.batchSizePercentage;
        }

        @CustomType.Setter
        public Builder batchSizePercentage(Integer batchSizePercentage) {
            if (batchSizePercentage == null) {
              throw new MissingRequiredPropertyException("OceanLaunchSpecUpdatePolicyRollConfig", "batchSizePercentage");
            }
            this.batchSizePercentage = batchSizePercentage;
            return this;
        }
        public OceanLaunchSpecUpdatePolicyRollConfig build() {
            final var _resultValue = new OceanLaunchSpecUpdatePolicyRollConfig();
            _resultValue.batchSizePercentage = batchSizePercentage;
            return _resultValue;
        }
    }
}
