// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Oceancd.Outputs
{

    [OutputType]
    public sealed class RolloutSpecSpotDeployment
    {
        /// <summary>
        /// Ocean CD cluster identifier for the references `SpotDeployment`.
        /// </summary>
        public readonly string? SpotDeploymentsClusterId;
        /// <summary>
        /// The name of the `SpotDeployment` resource
        /// </summary>
        public readonly string? SpotDeploymentsName;
        /// <summary>
        /// The namespace which the `SpotDeployment` resource exists within.
        /// </summary>
        public readonly string? SpotDeploymentsNamespace;

        [OutputConstructor]
        private RolloutSpecSpotDeployment(
            string? spotDeploymentsClusterId,

            string? spotDeploymentsName,

            string? spotDeploymentsNamespace)
        {
            SpotDeploymentsClusterId = spotDeploymentsClusterId;
            SpotDeploymentsName = spotDeploymentsName;
            SpotDeploymentsNamespace = spotDeploymentsNamespace;
        }
    }
}
