// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.spotinst.oceancd.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.spotinst.oceancd.outputs.StrategyRollingStep;
import java.util.List;
import java.util.Objects;

@CustomType
public final class StrategyRolling {
    /**
     * @return A set of separate conditions of rollout processing.
     * 
     */
    private List<StrategyRollingStep> steps;

    private StrategyRolling() {}
    /**
     * @return A set of separate conditions of rollout processing.
     * 
     */
    public List<StrategyRollingStep> steps() {
        return this.steps;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(StrategyRolling defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<StrategyRollingStep> steps;
        public Builder() {}
        public Builder(StrategyRolling defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.steps = defaults.steps;
        }

        @CustomType.Setter
        public Builder steps(List<StrategyRollingStep> steps) {
            if (steps == null) {
              throw new MissingRequiredPropertyException("StrategyRolling", "steps");
            }
            this.steps = steps;
            return this;
        }
        public Builder steps(StrategyRollingStep... steps) {
            return steps(List.of(steps));
        }
        public StrategyRolling build() {
            final var _resultValue = new StrategyRolling();
            _resultValue.steps = steps;
            return _resultValue;
        }
    }
}
