// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.spotinst.oceancd.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs extends com.pulumi.resources.ResourceArgs {

    public static final StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs Empty = new StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs();

    @Import(name="exact")
    private @Nullable Output<String> exact;

    public Optional<Output<String>> exact() {
        return Optional.ofNullable(this.exact);
    }

    @Import(name="prefix")
    private @Nullable Output<String> prefix;

    public Optional<Output<String>> prefix() {
        return Optional.ofNullable(this.prefix);
    }

    @Import(name="regex")
    private @Nullable Output<String> regex;

    public Optional<Output<String>> regex() {
        return Optional.ofNullable(this.regex);
    }

    private StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs() {}

    private StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs(StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs $) {
        this.exact = $.exact;
        this.prefix = $.prefix;
        this.regex = $.regex;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs $;

        public Builder() {
            $ = new StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs();
        }

        public Builder(StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs defaults) {
            $ = new StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs(Objects.requireNonNull(defaults));
        }

        public Builder exact(@Nullable Output<String> exact) {
            $.exact = exact;
            return this;
        }

        public Builder exact(String exact) {
            return exact(Output.of(exact));
        }

        public Builder prefix(@Nullable Output<String> prefix) {
            $.prefix = prefix;
            return this;
        }

        public Builder prefix(String prefix) {
            return prefix(Output.of(prefix));
        }

        public Builder regex(@Nullable Output<String> regex) {
            $.regex = regex;
            return this;
        }

        public Builder regex(String regex) {
            return regex(Output.of(regex));
        }

        public StrategyCanaryStepSetHeaderRouteMatchHeaderValueArgs build() {
            return $;
        }
    }

}
