// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Inputs
{

    public sealed class ElastigroupAzureV3SecretGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("sourceVaults", required: true)]
        private InputList<Inputs.ElastigroupAzureV3SecretSourceVaultGetArgs>? _sourceVaults;
        public InputList<Inputs.ElastigroupAzureV3SecretSourceVaultGetArgs> SourceVaults
        {
            get => _sourceVaults ?? (_sourceVaults = new InputList<Inputs.ElastigroupAzureV3SecretSourceVaultGetArgs>());
            set => _sourceVaults = value;
        }

        [Input("vaultCertificates", required: true)]
        private InputList<Inputs.ElastigroupAzureV3SecretVaultCertificateGetArgs>? _vaultCertificates;
        public InputList<Inputs.ElastigroupAzureV3SecretVaultCertificateGetArgs> VaultCertificates
        {
            get => _vaultCertificates ?? (_vaultCertificates = new InputList<Inputs.ElastigroupAzureV3SecretVaultCertificateGetArgs>());
            set => _vaultCertificates = value;
        }

        public ElastigroupAzureV3SecretGetArgs()
        {
        }
        public static new ElastigroupAzureV3SecretGetArgs Empty => new ElastigroupAzureV3SecretGetArgs();
    }
}
