// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.spotinst.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ElastigroupAzureV3VmSizesSpotSizeAttributes {
    private @Nullable Integer maxCpu;
    private @Nullable Integer maxMemory;
    private @Nullable Integer maxStorage;
    private @Nullable Integer minCpu;
    private @Nullable Integer minMemory;
    private @Nullable Integer minStorage;

    private ElastigroupAzureV3VmSizesSpotSizeAttributes() {}
    public Optional<Integer> maxCpu() {
        return Optional.ofNullable(this.maxCpu);
    }
    public Optional<Integer> maxMemory() {
        return Optional.ofNullable(this.maxMemory);
    }
    public Optional<Integer> maxStorage() {
        return Optional.ofNullable(this.maxStorage);
    }
    public Optional<Integer> minCpu() {
        return Optional.ofNullable(this.minCpu);
    }
    public Optional<Integer> minMemory() {
        return Optional.ofNullable(this.minMemory);
    }
    public Optional<Integer> minStorage() {
        return Optional.ofNullable(this.minStorage);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ElastigroupAzureV3VmSizesSpotSizeAttributes defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Integer maxCpu;
        private @Nullable Integer maxMemory;
        private @Nullable Integer maxStorage;
        private @Nullable Integer minCpu;
        private @Nullable Integer minMemory;
        private @Nullable Integer minStorage;
        public Builder() {}
        public Builder(ElastigroupAzureV3VmSizesSpotSizeAttributes defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.maxCpu = defaults.maxCpu;
    	      this.maxMemory = defaults.maxMemory;
    	      this.maxStorage = defaults.maxStorage;
    	      this.minCpu = defaults.minCpu;
    	      this.minMemory = defaults.minMemory;
    	      this.minStorage = defaults.minStorage;
        }

        @CustomType.Setter
        public Builder maxCpu(@Nullable Integer maxCpu) {

            this.maxCpu = maxCpu;
            return this;
        }
        @CustomType.Setter
        public Builder maxMemory(@Nullable Integer maxMemory) {

            this.maxMemory = maxMemory;
            return this;
        }
        @CustomType.Setter
        public Builder maxStorage(@Nullable Integer maxStorage) {

            this.maxStorage = maxStorage;
            return this;
        }
        @CustomType.Setter
        public Builder minCpu(@Nullable Integer minCpu) {

            this.minCpu = minCpu;
            return this;
        }
        @CustomType.Setter
        public Builder minMemory(@Nullable Integer minMemory) {

            this.minMemory = minMemory;
            return this;
        }
        @CustomType.Setter
        public Builder minStorage(@Nullable Integer minStorage) {

            this.minStorage = minStorage;
            return this;
        }
        public ElastigroupAzureV3VmSizesSpotSizeAttributes build() {
            final var _resultValue = new ElastigroupAzureV3VmSizesSpotSizeAttributes();
            _resultValue.maxCpu = maxCpu;
            _resultValue.maxMemory = maxMemory;
            _resultValue.maxStorage = maxStorage;
            _resultValue.minCpu = minCpu;
            _resultValue.minMemory = minMemory;
            _resultValue.minStorage = minStorage;
            return _resultValue;
        }
    }
}
