// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Aws.Inputs
{

    public sealed class ElastigroupIntegrationRancherArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The access key of the Rancher API.
        /// </summary>
        [Input("accessKey", required: true)]
        public Input<string> AccessKey { get; set; } = null!;

        /// <summary>
        /// The URL for the Nomad master host.
        /// </summary>
        [Input("masterHost", required: true)]
        public Input<string> MasterHost { get; set; } = null!;

        /// <summary>
        /// The secret key of the Rancher API.
        /// </summary>
        [Input("secretKey", required: true)]
        public Input<string> SecretKey { get; set; } = null!;

        /// <summary>
        /// The Rancher version. Must be `"1"` or `"2"`. If this field is omitted, it’s assumed that the Rancher cluster is version 1. Note that Kubernetes is required when using Rancher version 2^.
        /// Usage:
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public ElastigroupIntegrationRancherArgs()
        {
        }
    }
}
