// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SpotInst.Aws.Inputs
{

    public sealed class ManagedInstanceManagedInstanceActionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// String, Action type. Supported action types: `pause`, `resume`, `recycle`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public ManagedInstanceManagedInstanceActionArgs()
        {
        }
        public static new ManagedInstanceManagedInstanceActionArgs Empty => new ManagedInstanceManagedInstanceActionArgs();
    }
}
